function addChat(role,text){const box=document.getElementById('chatMessages');if(!box)return;const bubble=document.createElement('div');bubble.className=`chat-bubble ${role}`;bubble.innerHTML=`<b>${role==='sutra'?'Sutra':'You'}</b><p>${text}</p>`;box.appendChild(bubble);box.scrollTop=box.scrollHeight}
function aiEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function currentNode(){const ctx=JSON.parse(localStorage.getItem('sutra_current_context')||'null');const q=new URLSearchParams(location.search).get('node');return (window.SUTRA_HERITAGE||[]).find(x=>x.id===(q||ctx?.nodeId))||null}
function stateMatch(text){return (window.SUTRA_DATA?.states||[]).find(s=>text.includes(s.name.toLowerCase()))||null}
function districtMatch(text){for(const s of window.SUTRA_DATA?.states||[]){for(const d of s.districts||[]){const n=(typeof d==='string'?d:d.name).toLowerCase();if(text.includes(n))return {state:s,d:typeof d==='string'?{name:d,overview:`${d} is a featured district in ${s.name}.`,heritage:`Explore local heritage, food and cultural life in ${d}.`,food:s.dish,culture:s.culture,sourceName:s.sourceName||'Ministry of Tourism — India',sourceUrl:s.sourceUrl||'https://tourism.gov.in/'}:d}}}return null}
function answerFromNode(node){return `<b>${aiEsc(node.name)}</b> is a ${aiEsc((node.category||'heritage').toLowerCase())} experience in ${aiEsc(node.city)}, ${aiEsc(node.state)}. ${aiEsc(node.story)}<br><br><span class="ai-source-label">INDIAN SOURCE</span><br>${(node.sources||[]).map(s=>`✓ <a href="${s.url}" target="_blank" rel="noreferrer">${aiEsc(s.name)}</a>`).join('<br>')}<br><small>Grounded in the curated SUTRA-GEO dataset.</small>`}
function answerFromState(s){const districts=(s.districts||[]).map(d=>typeof d==='string'?d:d.name);return `<b>${aiEsc(s.name)}</b> is a SUTRA-GEO region focused on ${aiEsc(s.tagline)}. Its cultural layer includes ${aiEsc(s.culture)}. A signature food starting point is <b>${aiEsc(s.dish)}</b>.<br><br><b>Featured districts:</b> ${districts.map(aiEsc).join(' · ')}<br><br><span class="ai-source-label">INDIAN SOURCE</span><br>✓ <a href="${s.sourceUrl||'https://tourism.gov.in/'}" target="_blank" rel="noreferrer">${aiEsc(s.sourceName||'Ministry of Tourism — India')}</a>`}
function answerFromDistrict(state,d){return `<b>${aiEsc(d.name)}</b> is a featured district in <b>${aiEsc(state.name)}</b>. ${aiEsc(d.overview)}<br><br><b>Heritage:</b> ${aiEsc(d.heritage)}<br><b>Food:</b> ${aiEsc(d.food)}<br><b>Living culture:</b> ${aiEsc(d.culture)}<br><br><span class="ai-source-label">INDIAN SOURCE</span><br>✓ <a href="${d.sourceUrl||state.sourceUrl||'https://tourism.gov.in/'}" target="_blank" rel="noreferrer">${aiEsc(d.sourceName||state.sourceName||'Ministry of Tourism — India')}</a>`}
function answerFromFood(x){return `<b>${aiEsc(x.name)}</b> is featured in ${aiEsc(x.city)}, ${aiEsc(x.state)}. ${aiEsc(x.story)}<br><br><b>Where to start:</b> ${aiEsc(x.restaurant)} · ${aiEsc(x.price)}<br>${x.website?`<a href="${x.website}" target="_blank" rel="noreferrer">Open official food website ↗</a>`:''}`}
function answerFromEvent(x){return `<b>${aiEsc(x.name)}</b> is listed for ${aiEsc(x.city)}, ${aiEsc(x.state)}. ${aiEsc(x.desc)}<br><br><b>Date:</b> ${aiEsc(x.date)}<br><a href="${x.website}" target="_blank" rel="noreferrer">Open official event page ↗</a>`}
function aiBackendReady(){return !!(window.SUTRA_CONFIG?.features?.useBackendAskSutra&&window.SUTRA_CONFIG?.askSutra?.endpoint)}
async function askBackend(query,node){const endpoint=window.SUTRA_CONFIG.askSutra.endpoint;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,language:(SutraProfile.privacy().language||'en'),context:node?{id:node.id,name:node.name,city:node.city,state:node.state,story:node.story,sources:node.sources}:null})});if(!r.ok)throw new Error('backend unavailable');const data=await r.json();return data.answer||data.message||''}
async function askSutra(query){const text=query.toLowerCase().trim();const contextual=currentNode();let answer='';const district=districtMatch(text),state=stateMatch(text);let node=contextual;if(!node)for(const n of window.SUTRA_HERITAGE||[]){if(text.includes(n.name.toLowerCase())||text.includes(n.city.toLowerCase())||text.includes((n.district||'').toLowerCase())){node=n;break}}
 const food=(window.SUTRA_DATA?.food||[]).find(x=>text.includes(x.name.toLowerCase())||text.includes(x.city.toLowerCase())&&text.includes('food'));
 const event=(window.SUTRA_DATA?.events||[]).find(x=>text.includes(x.name.toLowerCase())||text.includes(x.city.toLowerCase())&&text.includes('event'));
 addChat('user',query);
 if(aiBackendReady()){try{const live=await askBackend(query,node);if(live){addChat('sutra',live);return}}catch(e){toast('Live AI connector unavailable · using grounded SUTRA mode.')}}
 if(node)answer=answerFromNode(node);else if(text.includes('food')&&food)answer=answerFromFood(food);else if((text.includes('event')||text.includes('festival'))&&event)answer=answerFromEvent(event);else if(district)answer=answerFromDistrict(district.state,district.d);else if(state)answer=answerFromState(state);else if(food)answer=answerFromFood(food);else if(event)answer=answerFromEvent(event);else if(text.includes('coin'))answer=`You currently have <b>${SutraWallet.get()} Sutra Coins</b>. Discoveries, daily quizzes, Heritage Micro-Quests, itineraries and approved community actions can contribute to the prototype wallet.`;else if(text.includes('quest'))answer=`SUTRA-GEO has two quest layers: a <b>Daily Sutra</b> with a once-per-day reward and a 10-question <b>Arena</b> competition. Heritage Nodes also open location-aware Micro-Quests.`;else if(text.includes('source')||text.includes('official'))answer='SUTRA-GEO uses Indian tourism and government sources in its grounded dataset. Open the source link on a place, state, district, food or event answer to inspect the reference.';else if(text.includes('book')||text.includes('restaurant')||text.includes('event'))answer='Open Food or Events from the navigation. Each listing now exposes its official website/event page in a new tab when one is available.';else answer='I can answer about SUTRA-GEO’s states, featured districts, heritage nodes, food, events, living heritage, quests and Sutra Coins. Try “tell me about West Bengal”, “what can I see in Agra?”, “food in Odisha” or “events in Rajasthan”.';setTimeout(()=>addChat('sutra',answer),180)}
document.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.page!=='ai')return;const mode=document.getElementById('aiMode');if(mode&&aiBackendReady())mode.textContent='Live backend connector enabled';const node=currentNode();if(node){const ctx=document.getElementById('aiContext');if(ctx)ctx.innerHTML=`<span class="tag">LOCATION AWARE</span><b>You are exploring ${aiEsc(node.name)}</b><span>${aiEsc(node.city)}, ${aiEsc(node.state)} · Ask Sutra is using this selected heritage context.</span>`;addChat('sutra',`You're exploring <b>${aiEsc(node.name)}</b>. Ask me about its history, craft, architecture or local context.<br><br>${answerFromNode(node)}`)}const form=document.getElementById('chatForm'),input=document.getElementById('chatText');form?.addEventListener('submit',e=>{e.preventDefault();const q=input?.value.trim();if(q){input.value='';askSutra(q)}})});window.askSutra=askSutra;
