const nodeId=new URLSearchParams(location.search).get('node')||'node-1';
let node=(window.SUTRA_HERITAGE||[]).find(n=>n.id===nodeId)||(window.SUTRA_HERITAGE||[])[0];let timer=null,remaining=30,selected=null,verified=false,distance=42;
function key(){return `sutra_quest_completed_${(SutraAuth.user().email||'guest').toLowerCase()}_${node.id}`}
function alreadyDone(){return localStorage.getItem(key())==='1'}
function renderNode(){document.getElementById('questNodeName').textContent=node.name;document.getElementById('questLocation').textContent=`${node.city}, ${node.state} · ${node.category}`;document.getElementById('questDistance').textContent=`${Math.round(distance)}m`;document.getElementById('questRadius').textContent=`${node.radius}m`;document.getElementById('questStory').textContent=node.story;document.getElementById('questQuestion').textContent=node.quest.question;document.getElementById('questOptions').innerHTML=node.quest.options.map((x,i)=>`<button class="micro-option" onclick="selectQuest(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('');document.getElementById('questResult').textContent=alreadyDone()?'This node quest has already been completed on this account. Revisit it for the story.':'';if(alreadyDone()){document.getElementById('startQuest').disabled=true;document.getElementById('startQuest').textContent='Quest already completed ✓'}}
function setContext(){localStorage.setItem('sutra_current_context',JSON.stringify({city:node.city,state:node.state,node:node.name,nodeId:node.id,updated:new Date().toISOString()}))}
function updateDistance(pos){distance=distanceMeters(pos.coords.latitude,pos.coords.longitude,node.lat,node.lng);document.getElementById('questDistance').textContent=`${Math.round(distance)}m`;const state=document.getElementById('questGeoState');verified=distance<=node.radius&&Number(pos.coords.accuracy||999)<=100;state.textContent=verified?'UNLOCKED':'OUTSIDE 50M';state.className=verified?'status-good':'';document.getElementById('questAccuracy').textContent=`±${Math.round(pos.coords.accuracy||999)}m`}
function checkLocation(){if(!navigator.geolocation){document.getElementById('questGeoState').textContent='DEMO MODE';return}navigator.geolocation.getCurrentPosition(updateDistance,()=>{document.getElementById('questGeoState').textContent='DEMO MODE'}, {enableHighAccuracy:true,maximumAge:5000,timeout:12000})}
function selectQuest(index){if(timer||alreadyDone())return;selected=index;document.querySelectorAll('.micro-option').forEach((b,i)=>b.classList.toggle('selected',i===index));document.getElementById('submitQuest').disabled=false}
function startQuest(){if(alreadyDone())return;if(timer)return;setContext();remaining=30;document.getElementById('questTimer').textContent=remaining;document.getElementById('questPhase').textContent='QUEST LIVE';document.getElementById('startQuest').disabled=true;document.getElementById('submitQuest').disabled=false;toast('30-second Heritage Micro-Quest started. Choose the correct answer.');timer=setInterval(()=>{remaining--;document.getElementById('questTimer').textContent=remaining;if(remaining<=0){clearInterval(timer);timer=null;submitQuest(true)}},1000)}
function submitQuest(timedOut=false){if(alreadyDone()){toast('This quest is already completed on this account.');return}if(selected===null){document.getElementById('questResult').textContent='Choose an answer first.';return}if(!verified&&!new URLSearchParams(location.search).has('demo')){document.getElementById('questResult').textContent='You are not inside the 50m geofence. Use Demo Unlock on the map for the prototype simulation.';return}const correct=selected===node.quest.answer;const result=document.getElementById('questResult');document.querySelectorAll('.micro-option').forEach((b,i)=>{if(i===node.quest.answer)b.classList.add('correct');if(i===selected&&i!==node.quest.answer)b.classList.add('wrong')});if(correct){localStorage.setItem(key(),'1');const firstDiscovery=!SutraNodeCapture.get().includes(node.id);SutraNodeCapture.capture(node.id,node.name,`${node.city} · ${node.state}`);if(firstDiscovery)SutraWallet.add(10,'Heritage Node discovered');result.innerHTML=`<b>✓ Quest Completed</b><br>+${node.quest.reward} Sutra Coins`;SutraWallet.add(node.quest.reward,`Heritage Micro-Quest: ${node.name}`);SutraJourney.add(node.city,node.state,node.name,'quest-completed');document.getElementById('questReward').hidden=false;document.getElementById('rewardCoins').textContent=`+${node.quest.reward}`;document.getElementById('startQuest').disabled=true;document.getElementById('submitQuest').disabled=true;document.getElementById('submitQuest').textContent='Completed ✓';}else{result.textContent=`Not quite. The answer is ${node.quest.options[node.quest.answer]}. ${timedOut?'The 30 seconds are up.':''}`;document.getElementById('submitQuest').disabled=true;document.getElementById('startQuest').disabled=false}}
window.selectQuest=selectQuest;window.startQuest=startQuest;window.submitQuest=submitQuest;
document.addEventListener('DOMContentLoaded',()=>{renderNode();checkLocation();document.getElementById('startQuest')?.addEventListener('click',startQuest);document.getElementById('submitQuest')?.addEventListener('click',()=>submitQuest(false))});
