const COMMUNITY_KEY='sutra_community_nodes';function getCommunity(){try{return JSON.parse(localStorage.getItem(COMMUNITY_KEY)||'[]')}catch{return[]}}function saveCommunity(x){localStorage.setItem(COMMUNITY_KEY,JSON.stringify(x))}
const BASE_STORIES=[{id:'base-hyd',title:'The recipe behind a festival sweet',place:'Hyderabad · Telangana',type:'Old recipe',text:'A family recipe remembered through festival mornings and shared with neighbours.',source:'Community memory',status:'Verified',verified:true},{id:'base-kutch',title:'The weaver lane story',place:'Kutch · Gujarat',type:'Craft tradition',text:'A memory about how textile patterns were taught from one generation to the next in a craft community.',source:'Local artisan',status:'Verified',verified:true},{id:'base-jaisalmer',title:'Songs that travel with the desert',place:'Jaisalmer · Rajasthan',type:'Oral history',text:'A local performance tradition carries stories of travel, weather and family memory across desert settlements.',source:'Community storyteller',status:'Verified',verified:true}];
function statusLabel(s){return s==='Verified'?'VERIFIED':s==='Published'?'PUBLISHED':s==='Under Review'?'UNDER REVIEW':'SUBMITTED'}
function renderCommunity(){const el=document.getElementById('communityList');if(!el)return;const user=(SutraAuth.user().email||'').toLowerCase();const items=[...getCommunity().filter(x=>x.status==='Published'||x.email===user),...BASE_STORIES];el.innerHTML=items.map(x=>`<article class="story-card"><div class="story-symbol">${x.type==='Craft tradition'?'🧵':x.type==='Old recipe'?'🍛':x.type==='Oral history'?'🎙️':'🪔'}</div><p class="eyebrow">${escapeHtml(x.type)} · ${escapeHtml(x.place)}</p><h2>${escapeHtml(x.title)}</h2><p>${escapeHtml(x.text)}</p><div class="quote">${statusLabel(x.status)} · Shared by ${escapeHtml(x.source||'community storyteller')}</div>${x.status!=='Published'&&x.email===user?`<p class="tiny">Your contribution: <b>${statusLabel(x.status)}</b></p>`:''}</article>`).join('')}
function submitStory(e){e.preventDefault();const u=SutraAuth.user();const email=(u.email||'').toLowerCase();const now=Date.now();const arr=getCommunity();const mine=arr.filter(x=>x.email===email);const recent=mine.find(x=>now-new Date(x.date).getTime()<30000);const today=mine.filter(x=>String(x.date).slice(0,10)===new Date().toISOString().slice(0,10)).length;if(recent){toast('Please wait a moment before submitting another story.');return}if(today>=5){toast('Prototype safety limit: 5 story submissions per account per day.');return}const item={id:`story-${Date.now()}`,email,title:storyTitle.value.trim(),place:storyPlace.value.trim(),type:storyType.value,text:storyText.value.trim(),source:storySource.value.trim()||'community storyteller',date:new Date().toISOString(),status:'Submitted',verified:false};arr.unshift(item);saveCommunity(arr);SutraScrapbook.save({title:item.title,place:item.place,type:'Community story',symbol:'🪔'});const media=document.getElementById('storyMedia')?.files?.[0];if(media&&window.SutraMedia){const u=SutraAuth.user();const parts=item.place.split(' · ');SutraMedia.put({id:`story-media-${Date.now()}`,email,kind:media.type.startsWith('video/')?'video':'photo',blob:media,city:parts[0]||item.place,state:parts[1]||'',node:'Community story',caption:item.title,created:new Date().toISOString()}).catch(()=>{});}e.target.reset();renderCommunity();renderModeration();toast('Story submitted. Status: Submitted → Under Review → Verified → Published.')}
function renderModeration(){const el=document.getElementById('moderationList');if(!el)return;const arr=getCommunity();el.innerHTML=arr.length?arr.map(x=>`<div class="moderation-row"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.place)} · ${statusLabel(x.status)}</small></div><div class="hero-actions">${x.status==='Submitted'?`<button class="small-btn" onclick="reviewStory('${x.id}')">Move to review</button>`:''}${x.status==='Under Review'?`<button class="small-btn primary" onclick="verifyStory('${x.id}')">Verify</button>`:''}${x.status==='Verified'?`<button class="small-btn primary" onclick="publishStory('${x.id}')">Publish</button>`:''}${x.status!=='Published'?`<button class="small-btn" onclick="rejectStory('${x.id}')">Reject</button>`:''}</div></div>`).join(''):'<p class="muted">No community submissions yet.</p>'}
function updateStory(id,status){const arr=getCommunity();const x=arr.find(y=>y.id===id);if(!x)return;x.status=status;x.verified=status==='Verified'||status==='Published';saveCommunity(arr);renderCommunity();renderModeration();toast(`Contribution status: ${status}`)}
function reviewStory(id){updateStory(id,'Under Review')}function verifyStory(id){updateStory(id,'Verified');const x=getCommunity().find(y=>y.id===id);if(x&&!x.rewarded){x.rewarded=true;saveCommunity(getCommunity());SutraWallet.add(20,'Verified community story')}}function publishStory(id){updateStory(id,'Published')}function rejectStory(id){updateStory(id,'Rejected')}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.reviewStory=reviewStory;window.verifyStory=verifyStory;window.publishStory=publishStory;window.rejectStory=rejectStory;document.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.page!=='community')return;renderCommunity();renderModeration();document.getElementById('storyForm')?.addEventListener('submit',submitStory)});
