(()=>{
const GAMES={
 rapid:{title:'Rapid Fire',kicker:'15 SECOND CHALLENGE'},memory:{title:'Memory Match',kicker:'MATCH THE PAIRS'},scramble:{title:'Word Scramble',kicker:'UNSCRAMBLE IT'},reaction:{title:'Tap Rush',kicker:'REACTION TEST'},guess:{title:'Guess the Place',kicker:'3 CLUES • 1 ANSWER'},match:{title:'Match It!',kicker:'PAIR IT FAST'},spinner:{title:'Coin Spinner',kicker:'SPIN FOR REWARDS'},geo:{title:'Geo Hunt',kicker:'LOCATION BONUS'},quiz:{title:'Challenge Arena',kicker:'5 ROUND CHALLENGE'}
};
const Q=[
['Which state is famous for Garba?',['Gujarat','Assam','Kerala','Bihar'],0],['Which city is known for the Charminar?',['Hyderabad','Jaipur','Kolkata','Pune'],0],['Pattachitra is strongly associated with?',['Odisha','Punjab','Goa','Bihar'],0],['Which festival is associated with Kerala?',['Onam','Bihu','Pongal','Gangaur'],0],['Muga silk is associated with?',['Assam','Gujarat','Rajasthan','Maharashtra'],0],['Hampi is linked to which empire?',['Vijayanagara','Maurya','Gupta','Pala'],0],['Banarasi weaving is associated with?',['Varanasi','Surat','Pune','Mysuru'],0],['Kuchipudi is associated with?',['Andhra Pradesh','Maharashtra','Assam','Goa'],0]
];
const WORDS=[['RAJASTHAN','JAIPUR'],['KUCHIPUDI','DANCE'],['PATTACHITRA','ART'],['CHARMINAR','MONUMENT'],['BATHUKAMMA','FESTIVAL'],['HIMALAYA','MOUNTAIN']];
const PAIRS=[['Garba','Gujarat'],['Onam','Kerala'],['Bihu','Assam'],['Pattachitra','Odisha'],['Lavani','Maharashtra'],['Madhubani','Bihar']];
const PLACES=[['Charminar',['I am in Hyderabad.','I was commissioned by the Qutb Shahi dynasty.','I have four grand arches.'],'Charminar'],['Hampi',['I am in Karnataka.','I was a major Vijayanagara centre.','My ruins are spread across a dramatic boulder landscape.'],'Hampi'],['Konark',['I am in Odisha.','I am shaped like a giant chariot.','I am dedicated to the Sun.'],'Konark Sun Temple'],['Amber Fort',['I am near Jaipur.','I sit on a hill.','I am a major Rajput-era fort.'],'Amber Fort']];
let state=JSON.parse(localStorage.getItem('sutra_arcade_state')||'null')||{coins:0,xp:0,wins:0,played:0,streak:0,bestReaction:null,daily:0,seen:[],high:0};
const save=()=>localStorage.setItem('sutra_arcade_state',JSON.stringify(state));
const $=id=>document.getElementById(id);
function refresh(){let level=Math.floor(state.xp/100)+1; $('levelNumber').textContent=level; $('coinStat').textContent=state.coins; $('completedStat').textContent=state.wins; $('badgeStat').textContent=Math.min(12,Math.floor(state.wins/3)); $('xpText').textContent=state.xp%100; $('xpFill').style.width=(state.xp%100)+'%'; $('streakStat').textContent=state.streak+' wins'; $('coinStrip').textContent=state.coins; $('missionGames').textContent=Math.min(3,state.daily)+' / 3'; $('missionWins').textContent=Math.min(5,state.wins)+' / 5'; $('bestReaction').textContent=state.bestReaction?state.bestReaction+' ms':'—'; renderLeaderboard();}
function reward(coins,xp=10){state.coins+=coins;state.xp+=xp;state.wins++;state.streak++;state.daily++;save();refresh();}
function lose(){state.streak=0;save();refresh();}
function open(title,kicker,body){$('gameModalContent').innerHTML=`<div class="modal-kicker">${kicker}</div><h2 class="modal-title">${title}</h2><p class="modal-sub">Play the round, then collect your reward.</p><div class="modal-game-area">${body}</div>`;$('gameModal').classList.add('show');$('gameModal').setAttribute('aria-hidden','false');}
window.closeGame=()=>{$('gameModal').classList.remove('show');$('gameModal').setAttribute('aria-hidden','true');};
window.launchGame=(id)=>{ if(id==='rapid') rapid(); else if(id==='memory') memory(); else if(id==='scramble') scramble(); else if(id==='reaction') reaction(); else if(id==='guess') guess(); else if(id==='match') match(); else if(id==='spinner') spinner(); else if(id==='geo') geo(); else quiz(); };
function rapid(){let i=0,score=0,t=15,timer;const draw=()=>{let q=Q[i%Q.length];$('gameModalContent').innerHTML=`<div class="modal-kicker">15 SECOND CHALLENGE</div><h2 class="modal-title">Rapid Fire</h2><div class="score-line"><span>Question ${i+1}</span><span id="rapidTimer">${t}s</span></div><div class="modal-game-area"><h3>${q[0]}</h3><div class="option-grid">${q[1].map((o,j)=>`<button onclick="window.rapidPick(${j},${q[2]})">${o}</button>`).join('')}</div><p class="result" id="rapidResult"></p></div>`};window.rapidPick=(j,a)=>{if(j===a){score++;state.xp+=5;state.coins+=5;$('rapidResult').textContent='✓ Nice! +5 coins';}else{$('rapidResult').textContent='✕ Keep going!';}i++;setTimeout(()=>{if(t>0)draw();},250)};draw();timer=setInterval(()=>{t--;let e=$('rapidTimer');if(e)e.textContent=t+'s';if(t<=0){clearInterval(timer);state.wins++;state.streak++;state.daily++;state.coins+=score*5;state.xp+=score*5;save();refresh();open('Round Complete','RAPID FIRE',`<h3>You scored ${score} points.</h3><p>+${score*5} bonus coins and XP.</p><div class="modal-actions"><button class="game-btn" onclick="closeGame()">Back to Arcade</button><button class="game-btn" onclick="launchGame('rapid')">Play Again</button></div>`)}},1000);}
function memory(){let icons=['🕌','🎨','🍛','🎭','🧵','🏛️'];let deck=[...icons,...icons].sort(()=>Math.random()-.5);let openIdx=[],matched=0,tries=0;const draw=()=>open('Memory Match','MEMORY',`<p>Find all six pairs.</p><div class="memory-grid">${deck.map((x,i)=>`<button class="memory-card ${openIdx.includes(i)?'open':''}" onclick="window.memPick(${i})">${openIdx.includes(i)||deck[i]==='MATCHED' ? deck[i]:'?'}</button>`).join('')}</div><p class="result">Pairs: ${matched}/6 · Tries: ${tries}</p>`);window.memPick=i=>{if(openIdx.includes(i)||deck[i]==='MATCHED'||openIdx.length===2)return;openIdx.push(i);draw();if(openIdx.length===2){tries++;setTimeout(()=>{let [a,b]=openIdx;if(deck[a]===deck[b]){deck[a]=deck[b]='MATCHED';matched++;}openIdx=[];if(matched===6){reward(80,50);open('Memory Complete','YOU WON',`<h3>Perfect match set! 🎉</h3><p>+80 coins · +50 XP</p><div class="modal-actions"><button class="game-btn" onclick="closeGame()">Back to Arcade</button></div>`)}else draw();},550)}};draw();}
function scramble(){let item=WORDS[Math.floor(Math.random()*WORDS.length)],word=item[0],scr=word.split('').sort(()=>Math.random()-.5).join('');open('Word Scramble','BRAIN',`<div class="scramble-word">${scr}</div><input id="scrambleInput" class="scramble-input" placeholder="Type the word"><div class="modal-actions"><button class="game-btn" onclick="window.checkScramble('${word}')">Submit</button></div><p class="result" id="scrambleResult"></p>`);window.checkScramble=w=>{let v=$('scrambleInput').value.trim().toUpperCase();if(v===w){reward(45,30);$('scrambleResult').textContent='✓ Correct! +45 coins';setTimeout(closeGame,900)}else{$('scrambleResult').textContent='✕ Not quite — try again.'}};}
function reaction(){open('Tap Rush','REACTION TEST',`<p>Press START, wait for GO, then tap the box as fast as possible.</p><div class="reaction-box" id="reactionBox" onclick="window.reactTap()">START</div><p class="result" id="reactionResult"></p>`);window.reactTimer=null;window.reactStart=0;window.reactReady=false;window.reactTap=()=>{let b=$('reactionBox');if(!window.reactReady){b.className='reaction-box wait';b.textContent='WAIT...';let delay=1000+Math.random()*2500;window.reactTimer=setTimeout(()=>{window.reactReady=true;window.reactStart=performance.now();b.className='reaction-box go';b.textContent='GO!'},delay);return}let ms=Math.round(performance.now()-window.reactStart);window.reactReady=false;if(!state.bestReaction||ms<state.bestReaction)state.bestReaction=ms;if(ms<500){reward(70,50);$('reactionResult').textContent=`⚡ ${ms} ms — new reaction result!`}else{reward(35,20);$('reactionResult').textContent=`${ms} ms — nice!`};setTimeout(closeGame,1100)};}
function guess(){let p=PLACES[Math.floor(Math.random()*PLACES.length)];open('Guess the Place','3 CLUES',`<div class="guess-clues">${p[1].map((c,i)=>`<div class="clue">Clue ${i+1}: ${c}</div>`).join('')}</div><div class="option-grid">${[p[2],...PLACES.filter(x=>x[2]!==p[2]).slice(0,3).map(x=>x[2])].sort(()=>Math.random()-.5).map(x=>`<button onclick="window.guessPick(this,'${p[2].replace(/'/g,"\'")}')">${x}</button>`).join('')}</div><p class="result" id="guessResult"></p>`);window.guessPick=(b,a)=>{if(b.textContent===a){reward(60,40);$('guessResult').textContent='✓ You got it!';}else{lose();$('guessResult').textContent='✕ Good try — the clues were the key.'}setTimeout(closeGame,900)};}
function match(){let p=PAIRS[Math.floor(Math.random()*PAIRS.length)],options=PAIRS.map(x=>x[1]).sort(()=>Math.random()-.5);open('Match It!','FAST MATCH',`<h3>Where does <b>${p[0]}</b> belong?</h3><div class="option-grid">${options.map(x=>`<button onclick="window.matchPick(this,'${p[1]}')">${x}</button>`).join('')}</div><p class="result" id="matchResult"></p>`);window.matchPick=(b,a)=>{if(b.textContent===a){reward(35,25);$('matchResult').textContent='✓ Correct match!'}else{lose();$('matchResult').textContent='✕ Wrong pair.'}setTimeout(closeGame,800)};}
function spinner(){open('Coin Spinner','SPIN FOR REWARDS',`<div class="spin-wheel" id="spinWheel"><div class="center-spin">SPIN</div></div><div class="modal-actions"><button class="game-btn" onclick="window.spinNow()">Spin Wheel</button></div><p class="result" id="spinResult"></p>`);window.spinNow=()=>{let w=$('spinWheel'),r=[20,30,50,75,100][Math.floor(Math.random()*5)];w.style.transform=`rotate(${720+Math.random()*360}deg)`;setTimeout(()=>{state.coins+=r;state.xp+=r>=75?30:10;state.wins++;state.streak++;state.daily++;save();refresh();$('spinResult').textContent=`🎉 You won ${r} coins!`;},1900)}};
function geo(){open('Geo Hunt','LOCATION BONUS',`<div style="text-align:center"><div style="font-size:60px">📍</div><h3>Unlock a nearby quest</h3><p>For demos, you can unlock this round instantly. Real location can be connected to your existing 50m geofence flow.</p><div class="modal-actions"><button class="game-btn" onclick="window.geoDemo()">Demo Unlock</button><button class="game-btn" onclick="window.geoLocate()">Use My Location</button></div><p class="result" id="geoResult"></p></div>`);window.geoDemo=()=>{reward(55,35);$('geoResult').textContent='🎯 Geo Quest unlocked! +55 coins';setTimeout(closeGame,1000)};window.geoLocate=()=>{if(!navigator.geolocation){$('geoResult').textContent='Location is not supported here.';return}navigator.geolocation.getCurrentPosition(()=>{reward(70,50);$('geoResult').textContent='📍 Location checked — quest bonus unlocked!';setTimeout(closeGame,1100)},()=>{$('geoResult').textContent='Location permission was not available. Use Demo Unlock for your presentation.'})};}
function quiz(){let round=0,score=0;const next=()=>{if(round>=5){state.coins+=score*10;state.xp+=score*10;state.wins++;state.streak++;state.daily++;save();refresh();open('Arena Complete','CHALLENGE ARENA',`<h3>You scored ${score}/5.</h3><p>+${score*10} coins · +${score*10} XP</p><div class="modal-actions"><button class="game-btn" onclick="closeGame()">Back to Arcade</button><button class="game-btn" onclick="launchGame('quiz')">Replay</button></div>`);return}let q=Q[(round+Math.floor(Math.random()*Q.length))%Q.length];open('Challenge Arena',`ROUND ${round+1} / 5`,`<div class="score-line"><span>Round ${round+1}</span><span>${score} correct</span></div><h3>${q[0]}</h3><div class="option-grid">${q[1].map((o,j)=>`<button onclick="window.quizPick(${j},${q[2]})">${o}</button>`).join('')}</div><p class="result" id="quizResult"></p>`)};window.quizPick=(j,a)=>{if(j===a){score++;$('quizResult').textContent='✓ Correct!'}else{$('quizResult').textContent='✕ Next round!'}round++;setTimeout(next,500)};next();}
function renderLeaderboard(){let base=[['You',state.xp],['HeritageHero',420],['CultureCrafter',365],['MapMaster',310],['StorySeeker',260]].sort((a,b)=>b[1]-a[1]);$('gameLeaderboard').innerHTML=base.map((x,i)=>`<div class="leader-row"><span class="rank">#${i+1}</span><div><b>${x[0]}</b><small> Player</small></div><strong>${x[1]} XP</strong></div>`).join('')}
$('randomGameBtn').onclick=()=>{let ids=Object.keys(GAMES);launchGame(ids[Math.floor(Math.random()*ids.length)]);};$('continueBtn').onclick=()=>launchGame('quiz');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');let f=b.dataset.filter;document.querySelectorAll('.game-card').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.type!==f));});refresh();
})();
