function distanceMeters(lat1,lon1,lat2,lon2){const R=6371000,rad=Math.PI/180,dLat=(lat2-lat1)*rad,dLon=(lon2-lon1)*rad;const a=Math.sin(dLat/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
window.distanceMeters=distanceMeters;
function nodeStorageKey(){return 'sutra_geofence_seen_'+(SutraAuth.user().email||'guest').toLowerCase()}
function seenNodes(){try{return JSON.parse(localStorage.getItem(nodeStorageKey())||'[]')}catch{return[]}}
function markSeen(id){const x=seenNodes();if(!x.includes(id)){x.push(id);localStorage.setItem(nodeStorageKey(),JSON.stringify(x))}}
function playChime(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(660,c.currentTime);o.frequency.exponentialRampToValueAtTime(990,c.currentTime+.16);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.08,c.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.32);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.34)}catch(e){}}
function showGeofenceStatus(n,distance,status='LOCKED',accuracy=null){const panel=document.getElementById('geofenceStatus');if(!panel)return;const warning=accuracy&&accuracy>100?`<p class="geo-warning">Location accuracy is ±${Math.round(accuracy)}m. You can see your position, but a 50–100m quest unlock needs better accuracy.</p>`:'';panel.innerHTML=`<div class="geo-status-row"><div><span class="tag">GEOFENCE · ${n.radius}M</span><h3>${n.emoji||'📍'} ${n.name}</h3><p>${n.city}, ${n.state} · ${n.category}</p></div><div class="geo-distance"><strong>${Math.round(distance)}m</strong><span>from nearest node</span></div></div><div class="geo-status-meta"><span>Radius: <b>${n.radius}m</b></span><span>Status: <b class="${status==='UNLOCKED'?'status-good':''}">${status}</b></span><span>Accuracy: <b>±${accuracy?Math.round(accuracy):'—'}m</b></span></div>${warning}`}
function showUserLocation(lat,lng,accuracy){if(window.SUTRA_MAP&&window.L){const m=window.SUTRA_MAP;if(window.SUTRA_USER_MARKER)m.removeLayer(window.SUTRA_USER_MARKER);if(window.SUTRA_ACCURACY_CIRCLE)m.removeLayer(window.SUTRA_ACCURACY_CIRCLE);window.SUTRA_USER_MARKER=L.marker([lat,lng],{title:'Your location'}).addTo(m).bindPopup(`<b>Your location</b><br>Accuracy ±${Math.round(accuracy||0)}m`);window.SUTRA_ACCURACY_CIRCLE=L.circle([lat,lng],{radius:Math.min(Number(accuracy)||50,500),color:'#a74e35',fillOpacity:.08}).addTo(m);m.setView([lat,lng],Math.max(m.getZoom(),11));setTimeout(()=>m.invalidateSize(),100)}}
function unlockNode(n,distance){const first=!seenNodes().includes(n.id);markSeen(n.id);playChime();if(first)SutraWallet.add(10,`Heritage Node discovered: ${n.name}`);localStorage.setItem('sutra_current_context',JSON.stringify({city:n.city,state:n.state,node:n.name,nodeId:n.id,updated:new Date().toISOString()}));SutraJourney.add(n.city,n.state,n.name,'geofence');showGeofenceStatus(n,distance,'UNLOCKED',5);const panel=document.getElementById('nodeUnlockPanel');if(panel){panel.classList.add('open');panel.innerHTML=`<div><span class="tag">HERITAGE NODE UNLOCKED</span><h2>${n.name}</h2><p><b>You are ${Math.round(distance)}m away.</b> · ${n.city}, ${n.state}</p><p>${n.shortStory}</p><a class="btn btn-primary" href="ar.html?node=${encodeURIComponent(n.id)}">Start Heritage Micro-Quest →</a><a class="btn btn-ghost" href="ai.html?node=${encodeURIComponent(n.id)}" style="margin-left:8px">Ask Sutra about this place</a></div>`}}
function processPosition(pos){if(!SutraSettings.locationEnabled()){toast('Location access is off in your privacy settings.');return}const lat=pos.coords.latitude,lng=pos.coords.longitude,accuracy=Number(pos.coords.accuracy||999);showUserLocation(lat,lng,accuracy);if(lastPosition){const d=distanceMeters(lastPosition.lat,lastPosition.lng,lat,lng),dt=(pos.timestamp-lastPosition.time)/1000;if(dt>0&&d/dt>60){toast('Movement check paused an impossible location jump.');return}}lastPosition={lat,lng,time:pos.timestamp};const nodes=(window.SUTRA_GEOFENCE_NODES||[]).map(n=>({...n,distance:distanceMeters(lat,lng,n.lat,n.lng)})).sort((a,b)=>a.distance-b.distance);const closest=nodes[0];if(!closest)return;const unlocked=closest.distance<=closest.radius&&accuracy<=100;showGeofenceStatus(closest,closest.distance,unlocked?'UNLOCKED':'LOCKED',accuracy);if(unlocked&&!seenNodes().includes(closest.id))unlockNode(closest,closest.distance);else if(closest.distance<=closest.radius&&accuracy>100)toast(`You're near ${closest.name}, but GPS accuracy is ±${Math.round(accuracy)}m. Move outdoors for a reliable unlock.`)}
let lastPosition=null,watchId=null;
function geoError(err){const msg=err?.code===1?'Location permission was denied. Allow Location for this site and try again.':err?.code===2?'Your browser could not determine a position. Check Windows Location Services and try again.':'Location request timed out. Try again in an open area.';toast(msg)}
function startGeofenceWatch(){if(!SutraSettings.locationEnabled()){toast('Enable Location Access in Profile to use Heritage Radar.');return}if(!navigator.geolocation){toast('Location is not supported by this browser.');return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);toast('Heritage radar is listening for nearby nodes…');watchId=navigator.geolocation.watchPosition(processPosition,geoError,{enableHighAccuracy:true,maximumAge:0,timeout:20000})}
function stopGeofenceWatch(){if(watchId!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId);watchId=null}toast('Heritage radar stopped.')}
function checkNearbyHeritage(){if(!SutraSettings.locationEnabled()){toast('Enable Location Access in Profile to use Heritage Radar.');return}if(!navigator.geolocation){toast('Location is not supported by this browser.');return}toast('Finding your location…');navigator.geolocation.getCurrentPosition(processPosition,geoError,{enableHighAccuracy:true,maximumAge:0,timeout:20000})}
function simulateHeritageUnlock(){const n=(window.SUTRA_GEOFENCE_NODES||[])[0];if(!n)return;localStorage.setItem('sutra_demo_location',JSON.stringify({lat:n.lat,lng:n.lng,accuracy:5,simulated:true}));showUserLocation(n.lat,n.lng,5);unlockNode(n,42);toast(`Demo location active · 42m from ${n.name}`)}
window.startGeofenceWatch=startGeofenceWatch;window.stopGeofenceWatch=stopGeofenceWatch;window.checkNearbyHeritage=checkNearbyHeritage;window.simulateHeritageUnlock=simulateHeritageUnlock;
