const SUTRA_PLACES=[
...(window.SUTRA_HERITAGE||[]).map(x=>({name:x.name,city:x.city,state:x.state,lat:x.lat,lng:x.lng,type:x.category==='Craft'?'culture':'heritage',emoji:x.emoji,story:x.shortStory,nodeId:x.id,image:x.image,source:x.sources?.[0],category:x.category})),
...((window.SUTRA_DATA?.food||[]).map(x=>({name:x.name,city:x.city,state:x.state,lat:(window.SUTRA_DISTRICTS?.[x.state]?.find(d=>d.name===x.city)?.lat||0),lng:(window.SUTRA_DISTRICTS?.[x.state]?.find(d=>d.name===x.city)?.lng||0),type:'food',emoji:'🍛',story:x.story,image:x.image,category:'Food',source:{name:x.restaurant,url:x.website}})).filter(x=>x.lat&&x.lng)),
...((window.SUTRA_DATA?.events||[]).map(x=>({name:x.name,city:x.city,state:x.state,lat:(window.SUTRA_DISTRICTS?.[x.state]?.find(d=>d.name===x.city)?.lat||0),lng:(window.SUTRA_DISTRICTS?.[x.state]?.find(d=>d.name===x.city)?.lng||0),type:'culture',emoji:'🎭',story:x.desc,image:x.image,category:'Event',source:{name:'Official event page',url:x.website}})).filter(x=>x.lat&&x.lng)),
{name:'Kathakali Centre',city:'Kochi',state:'Kerala',lat:9.9312,lng:76.2673,type:'culture',emoji:'🎭',story:'Performance traditions become a gateway into Kerala culture.',category:'Music & Dance'},
{name:'Majuli Island',city:'Majuli',state:'Assam',lat:27.0016,lng:94.2243,type:'culture',emoji:'🎨',story:'Island communities, mask-making and satra traditions.',category:'Local Tradition'},
{name:'Munnar Tea Country',city:'Munnar',state:'Kerala',lat:10.0889,lng:77.0595,type:'nature',emoji:'🌿',story:'Tea landscapes shaped by people, work and mountain ecology.',category:'Nature'}
]
let sutraMap;const markerLayers={};window.SUTRA_MAP=null;
function esc(v){return String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function nodeDetail(id){return (window.SUTRA_HERITAGE||[]).find(x=>x.id===id)}
function popupFor(p){const n=nodeDetail(p.nodeId);const captured=p.nodeId&&SutraNodeCapture.get().includes(p.nodeId);const source=n?.sources?.[0];return `<div class="sutra-popup"><span class="tag">${p.nodeId?'HERITAGE NODE':'DISCOVERY'}</span><h3>${p.emoji} ${esc(p.name)}</h3><p><b>${esc(p.city)}</b>, ${esc(p.state)} · ${esc(p.category||'Cultural discovery')}</p>${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" style="width:100%;height:120px;object-fit:cover;border-radius:10px;margin:8px 0">`:''}<small>${esc(p.story)}</small>${n?`<p class="tiny"><b>Geofence:</b> ${n.radius}m · <b>Status:</b> ${captured?'VISITED':'LOCKED'}</p><p class="tiny"><b>Nearby experience:</b> ${esc(n.artisan?.experience||'Local cultural experience')}</p>`:''}${source?`<a class="map-save" href="${source.url}" target="_blank" rel="noreferrer">Source ↗</a>`:''}<button class="map-save" type="button" onclick="saveMapPlace('${esc(p.name)}','${esc(p.city)}','${esc(p.state)}')">Save to scrapbook</button>${p.nodeId?`<a class="map-save" href="ar.html?node=${encodeURIComponent(p.nodeId)}">Start Micro-Quest</a><button class="map-save" type="button" onclick="captureMapNode('${esc(p.nodeId)}','${esc(p.name)}','${esc(p.city)}','${esc(p.state)}')">${captured?'✓ Revisit node':'Open + verify node'}</button>`:''}</div>`}
function initSutraMap(){if(document.body.dataset.page!=='map'||typeof L==='undefined')return;const el=document.getElementById('indiaMap');if(!el)return;sutraMap=L.map(el).setView([22.5,79],5);window.SUTRA_MAP=sutraMap;setTimeout(()=>sutraMap.invalidateSize(),120);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(sutraMap);['heritage','food','culture','nature'].forEach(t=>markerLayers[t]=L.layerGroup().addTo(sutraMap));SUTRA_PLACES.forEach(p=>{if(!markerLayers[p.type])return;markerLayers[p.type].addLayer(L.marker([p.lat,p.lng]).bindPopup(popupFor(p),{maxWidth:330}))});const params=new URLSearchParams(location.search),state=params.get('state'),city=params.get('city');if(city){const cm=SUTRA_PLACES.filter(p=>p.city===city||p.name===city);if(cm.length)sutraMap.fitBounds(L.latLngBounds(cm.map(p=>[p.lat,p.lng])),{padding:[30,30],maxZoom:13})}else if(state){const matches=SUTRA_PLACES.filter(p=>p.state===state);if(matches.length)sutraMap.fitBounds(L.latLngBounds(matches.map(p=>[p.lat,p.lng])),{padding:[30,30],maxZoom:8})}}
function filterMap(type,show){if(!sutraMap||!markerLayers[type])return;show?markerLayers[type].addTo(sutraMap):sutraMap.removeLayer(markerLayers[type])}
function focusMap(){const state=document.getElementById('mapState')?.value||'all';const city=document.getElementById('mapCity')?.value||'all';const matches=SUTRA_PLACES.filter(p=>(state==='all'||p.state===state)&&(city==='all'||p.city===city));if(matches.length===1)sutraMap.setView([matches[0].lat,matches[0].lng],13);else if(matches.length)sutraMap.fitBounds(L.latLngBounds(matches.map(p=>[p.lat,p.lng])),{padding:[30,30],maxZoom:8})}
function fillMapControls(){const state=document.getElementById('mapState');const city=document.getElementById('mapCity');if(!state||!city)return;const states=[...new Set(SUTRA_PLACES.map(x=>x.state))].sort();state.innerHTML='<option value="all">All India</option>'+states.map(x=>`<option>${x}</option>`).join('');const update=()=>{const cities=[...new Set(SUTRA_PLACES.filter(x=>state.value==='all'||x.state===state.value).map(x=>x.city))].sort();city.innerHTML='<option value="all">All cities</option>'+cities.map(x=>`<option>${x}</option>`).join('')};state.addEventListener('change',()=>{update();focusMap()});city.addEventListener('change',focusMap);update()}
function saveMapPlace(name,city,state){const r=SutraScrapbook.save({title:name,place:`${city} · ${state}`,type:'Map discovery',symbol:'📍'});if(r.added){SutraJourney.add(city,state,name,'saved-place');SutraWallet.add(10,`Heritage discovery: ${name}`);toast(`${name} saved to your scrapbook · +10 coins ✦`)}else toast(`${name} is already in your scrapbook.`)}
function captureMapNode(id,name,city,state){localStorage.setItem('sutra_current_context',JSON.stringify({city,state,node:name,nodeId:id,updated:new Date().toISOString(),demo:true}));location.href=`ar.html?node=${encodeURIComponent(id)}&demo=1`}
window.saveMapPlace=saveMapPlace;window.captureMapNode=captureMapNode;window.filterMap=filterMap;window.focusMap=focusMap;document.addEventListener('DOMContentLoaded',()=>{initSutraMap();fillMapControls()});
