let passportMedia=[];let passportCities=[];
function passportJourney(){return SutraJourney.forUser()}
function cityKey(x){return `${x.city}|${x.state}`}
function getPassportCities(){const map=new Map();passportJourney().forEach(x=>{if(!x.city)return;const k=cityKey(x);if(!map.has(k))map.set(k,{city:x.city,state:x.state})});passportMedia.forEach(x=>{if(!x.city)return;const k=cityKey(x);if(!map.has(k))map.set(k,{city:x.city,state:x.state})});return [...map.values()]}
function renderVouchers(){const el=document.getElementById('voucherList');if(!el)return;const arr=JSON.parse(localStorage.getItem('sutra_vouchers_'+(SutraAuth.user().email||'guest').toLowerCase())||'[]');el.innerHTML=arr.length?arr.map(x=>`<div class="voucher-row"><b>${escapeHtml(x.title)}</b><span>${escapeHtml(x.code)}</span><small>${escapeHtml(x.city)} · ${new Date(x.date).toLocaleDateString('en-IN')}</small></div>`).join(''):'<p class="muted">No redeemed experiences yet.</p>'}
function renderPassport(){passportCities=getPassportCities();const stats=document.getElementById('passportStates'),places=document.getElementById('passportPlaces'),grid=document.getElementById('cityPassportGrid');const journey=passportJourney();const states=new Set(passportCities.map(x=>x.state));if(stats)stats.textContent=states.size;if(places)places.textContent=passportCities.length;if(document.getElementById('passportQuestCount'))document.getElementById('passportQuestCount').textContent=journey.filter(x=>x.type==='quest-completed').length;if(document.getElementById('passportStoryCount'))document.getElementById('passportStoryCount').textContent=JSON.parse(localStorage.getItem('sutra_community_nodes')||'[]').filter(x=>x.email===(SutraAuth.user().email||'').toLowerCase()).length;grid.innerHTML=passportCities.length?passportCities.map(x=>{const m=passportMedia.filter(y=>cityKey(y)===cityKey(x));const sites=[...new Set(journey.filter(y=>cityKey(y)===cityKey(x)&&y.node).map(y=>y.node))];const qs=journey.filter(y=>cityKey(y)===cityKey(x)&&y.type==='quest-completed').length;return `<button class="city-passport-card" onclick="openCityPassport('${x.city.replace(/'/g,"\\'")}','${x.state.replace(/'/g,"\\'")}')"><span class="city-stamp">✦</span><b>${x.city}</b><small>${x.state}</small><div>${sites.length||0} sites · ${qs} quests</div><div>📸 ${m.filter(y=>y.kind==='photo').length} · 🎥 ${m.filter(y=>y.kind==='video').length}</div></button>`}).join(''):'<div class="empty-state" style="grid-column:1/-1"><span>🧭</span><h2>Your passport is waiting.</h2><p>Unlock a Heritage Node or upload a memory to start your city journey.</p><a class="btn btn-primary" href="map.html">Explore the map →</a></div>'}
async function openCityPassport(city,state){document.getElementById('cityDetail').hidden=false;document.getElementById('cityDetailTitle').textContent=city;document.getElementById('cityDetailSub').textContent=`${state} · Your personal heritage journey`;const journey=passportJourney().filter(x=>x.city===city&&x.state===state);const media=passportMedia.filter(x=>x.city===city&&x.state===state);const sites=[...new Set(journey.filter(x=>x.node).map(x=>x.node))];document.getElementById('citySites').textContent=sites.length;document.getElementById('cityQuests').textContent=journey.filter(x=>x.type==='quest-completed').length;document.getElementById('cityPhotos').textContent=media.filter(x=>x.kind==='photo').length;document.getElementById('cityVideos').textContent=media.filter(x=>x.kind==='video').length;const nodeNames=new Set(journey.map(x=>x.node).filter(Boolean));const history=JSON.parse(localStorage.getItem(SutraWallet.historyKey())||'[]');const earned=history.filter(x=>x.amount>0&&[...nodeNames].some(n=>String(x.label).includes(n))).reduce((a,x)=>a+x.amount,0);document.getElementById('cityCoins').textContent=earned;const photos=media.filter(x=>x.kind==='photo'),videos=media.filter(x=>x.kind==='video');
const renderMediaCard=x=>{const url=URL.createObjectURL(x.blob);return `<article class="media-card">${x.kind==='video'?`<video src="${url}" controls></video>`:`<img src="${url}" alt="${escapeHtml(x.caption||x.node||city)}">`}<div><b>${escapeHtml(x.node||city)}</b><p>${escapeHtml(x.caption||'Heritage memory')}</p><small>📍 ${city}, ${state}</small></div></article>`};
const groupMedia=arr=>{const groups=new Map();arr.forEach(x=>{const k=x.node||'City memory';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});return [...groups].map(([k,items])=>`<section class="passport-media-group"><p class="eyebrow">${escapeHtml(k)}</p><div class="media-grid">${items.map(renderMediaCard).join('')}</div></section>`).join('')};
document.getElementById('cityPhotosGrid').innerHTML=photos.length?groupMedia(photos):'<div class="empty-state" style="grid-column:1/-1;padding:28px"><span>📸</span><h3>No photos yet</h3><p>Add a photo from your profile.</p></div>';
document.getElementById('cityVideosGrid').innerHTML=videos.length?groupMedia(videos):'<div class="empty-state" style="grid-column:1/-1;padding:28px"><span>🎥</span><h3>No videos yet</h3><p>Add a short video from your profile.</p></div>';
const timeline=[...journey.map(x=>({date:x.date,node:x.node,type:x.type})),...media.map(x=>({date:x.created,node:x.node,type:x.kind==='video'?'Video uploaded':'Photo uploaded'}))].sort((a,b)=>new Date(a.date)-new Date(b.date));document.getElementById('cityTimeline').innerHTML=timeline.length?timeline.map(x=>`<div class="timeline-item"><time>${new Date(x.date).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</time><div><b>📍 ${escapeHtml(x.node||city)}</b><span>${x.type==='quest-completed'?'✓ Quest completed':x.type==='video-upload'?'🎥 Video added':x.type==='photo-upload'?'📸 Photo added':x.type}</span></div></div>`).join(''):'<p class="muted">Your journey timeline will appear here.</p>';document.getElementById('cityDetail').scrollIntoView({behavior:'smooth',block:'start'})}
function filterCityMedia(type){document.querySelectorAll('#cityMedia .media-card').forEach(el=>{el.style.display=(type==='all'||el.dataset.kind===type)?'block':'none'})}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('DOMContentLoaded',async()=>{if(document.body.dataset.page!=='passport')return;passportMedia=await SutraMedia.all();renderPassport();renderVouchers();document.getElementById('cityDetailClose')?.addEventListener('click',()=>document.getElementById('cityDetail').hidden=true)});
